// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      //throw UnsupportedError(
      //  'DefaultFirebaseOptions have not been configured for web - '
      //  'you can reconfigure this by running the FlutterFire CLI again.',
      //);
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTQTjuctWA9XnkAcl5_O3w5I9h_eL0lSk',
    appId: '1:1070536871755:android:17306884650e8d9501a2ce',
    messagingSenderId: '1070536871755',
    projectId: 'movilesii-ffaab',
    storageBucket: 'movilesii-ffaab.firebasestorage.app',
  );

  // Your web app's Firebase configuration
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD39OnpnlHTJXgvXZlPrSKKcAfCtEGHxJA',
    authDomain: 'movilesii-ffaab.firebaseapp.com',
    projectId: 'movilesii-ffaab',
    storageBucket: 'movilesii-ffaab.firebasestorage.app',
    messagingSenderId: '1070536871755',
    appId: '1:1070536871755:web:bb7967f98c3cbe9d01a2ce',
    measurementId: 'G-B4H19G0B9R',
  );
  //
}
